language: node_js
node_js: node
script:
- npm run typedoc
deploy:
  matrix:
  - provider: surge
    skip_cleanup: true
    on:
      tags: true
      repo: calculemuscode/oli-hammock
    project: "./typedoc/"
    domain: oli-hammock.surge.sh
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
      repo: calculemuscode/oli-hammock
    email: rob@calculem.us
    api_key:
      secure: rL4T3TaRNY6zmKVbFQdJYDbCLELGENGorWSPkPDdptrqwe/de90WNw0FSp8OxtbH8erfoyZap8SuY7rhxLBDdPRJeLmqtAM8Pmz/ngLyKgPbpX3XrxOQmOnS0IMllvDy9TA1lxm1Ow8sloLkgcJc1eiNaqy0FwbZlSLYMmOZTDxwO/7iF4hLJISfLIUWcVw4hOfqxkYnAapDItjNveWghlhk22GDK2R8FVLGdkxkbV3oXuMhddDaGeZbRKaypbfCXYOtHYhnr1lUGMsAGjF5RF80jzmllAoW7oxldp19thMyoP4MkhfgjNR9VSkENhFatUDWaQExULUOpFuhzpxZeTqholU9kaHRC6gPaWubeJadUcGGLybruJ6s7oJTJd/xygN8qnoXZxbnY3Rpw3x8LQv17T7TQlfxzscYiPA2gCgRvKFI3Gt2sbBcIEF7e81IvxnBH8at2TOp3nwj6iilLXo0bQE7jMhCWdycKJ6he+zEwXdWSQT7lZUhhF6ECdD7wfR8LH3WfgAtbtaeJXCU6pCaGV4CN3sO4luSC4T9lksIVttXMBLlnMxbKwn8AeJn8f2cLTUKjWODj48mBicG/BiaJPMxfCuyvrgPwbR4Z7NYbL8BjUi8vlrDateCX5kXC75R8ElR/O6NFCZvNZMkkemLYj2IDhEv054TZxIslMA=
